/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsesRouteImport } from './routes/uses'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as TagGalaxyRouteImport } from './routes/tag-galaxy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OgRouteImport } from './routes/og'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ItemGalaxyRouteImport } from './routes/item-galaxy'
import { Route as GalaxyRouteImport } from './routes/galaxy'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TagsTagSlugRouteImport } from './routes/tags.$tagSlug'
import { Route as PeoplePersonSlugRouteImport } from './routes/people.$personSlug'
import { Route as LikeTagRouteImport } from './routes/like/$tag'
import { Route as ItemsItemSlugRouteImport } from './routes/items.$itemSlug'
import { Route as ApiSiteManagementRouteImport } from './routes/api.site-management'
import { Route as AdminToolsRouteImport } from './routes/admin/tools'
import { Route as AdminTagsRouteImport } from './routes/admin/tags'
import { Route as AdminScrapeRouteImport } from './routes/admin/scrape'
import { Route as AdminReviewRouteImport } from './routes/admin/review'
import { Route as AdminMergeRouteImport } from './routes/admin/merge'
import { Route as AdminItemsRouteImport } from './routes/admin/items'
import { Route as AdminErrorsRouteImport } from './routes/admin/errors'
import { Route as AdminBatchRouteImport } from './routes/admin/batch'
import { Route as AdminAwardsRouteImport } from './routes/admin/awards'

const UsesRoute = UsesRouteImport.update({
  id: '/uses',
  path: '/uses',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const TagGalaxyRoute = TagGalaxyRouteImport.update({
  id: '/tag-galaxy',
  path: '/tag-galaxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemGalaxyRoute = ItemGalaxyRouteImport.update({
  id: '/item-galaxy',
  path: '/item-galaxy',
  getParentRoute: () => rootRouteImport,
} as any)
const GalaxyRoute = GalaxyRouteImport.update({
  id: '/galaxy',
  path: '/galaxy',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TagsTagSlugRoute = TagsTagSlugRouteImport.update({
  id: '/$tagSlug',
  path: '/$tagSlug',
  getParentRoute: () => TagsRoute,
} as any)
const PeoplePersonSlugRoute = PeoplePersonSlugRouteImport.update({
  id: '/people/$personSlug',
  path: '/people/$personSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LikeTagRoute = LikeTagRouteImport.update({
  id: '/like/$tag',
  path: '/like/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsItemSlugRoute = ItemsItemSlugRouteImport.update({
  id: '/items/$itemSlug',
  path: '/items/$itemSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSiteManagementRoute = ApiSiteManagementRouteImport.update({
  id: '/api/site-management',
  path: '/api/site-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminToolsRoute = AdminToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScrapeRoute = AdminScrapeRouteImport.update({
  id: '/scrape',
  path: '/scrape',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMergeRoute = AdminMergeRouteImport.update({
  id: '/merge',
  path: '/merge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminItemsRoute = AdminItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AdminRoute,
} as any)
const AdminErrorsRoute = AdminErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBatchRoute = AdminBatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAwardsRoute = AdminAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/admin': typeof AdminRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/galaxy': typeof GalaxyRoute
  '/item-galaxy': typeof ItemGalaxyRoute
  '/mcp': typeof McpRoute
  '/og': typeof OgRoute
  '/products': typeof ProductsRoute
  '/tag-galaxy': typeof TagGalaxyRoute
  '/tags': typeof TagsRouteWithChildren
  '/uses': typeof UsesRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/batch': typeof AdminBatchRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/merge': typeof AdminMergeRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/scrape': typeof AdminScrapeRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/tools': typeof AdminToolsRoute
  '/api/site-management': typeof ApiSiteManagementRoute
  '/items/$itemSlug': typeof ItemsItemSlugRoute
  '/like/$tag': typeof LikeTagRoute
  '/people/$personSlug': typeof PeoplePersonSlugRoute
  '/tags/$tagSlug': typeof TagsTagSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/discover': typeof DiscoverRoute
  '/galaxy': typeof GalaxyRoute
  '/item-galaxy': typeof ItemGalaxyRoute
  '/mcp': typeof McpRoute
  '/og': typeof OgRoute
  '/products': typeof ProductsRoute
  '/tag-galaxy': typeof TagGalaxyRoute
  '/tags': typeof TagsRouteWithChildren
  '/uses': typeof UsesRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/batch': typeof AdminBatchRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/merge': typeof AdminMergeRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/scrape': typeof AdminScrapeRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/tools': typeof AdminToolsRoute
  '/api/site-management': typeof ApiSiteManagementRoute
  '/items/$itemSlug': typeof ItemsItemSlugRoute
  '/like/$tag': typeof LikeTagRoute
  '/people/$personSlug': typeof PeoplePersonSlugRoute
  '/tags/$tagSlug': typeof TagsTagSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/admin': typeof AdminRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/galaxy': typeof GalaxyRoute
  '/item-galaxy': typeof ItemGalaxyRoute
  '/mcp': typeof McpRoute
  '/og': typeof OgRoute
  '/products': typeof ProductsRoute
  '/tag-galaxy': typeof TagGalaxyRoute
  '/tags': typeof TagsRouteWithChildren
  '/uses': typeof UsesRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/batch': typeof AdminBatchRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/merge': typeof AdminMergeRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/scrape': typeof AdminScrapeRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/tools': typeof AdminToolsRoute
  '/api/site-management': typeof ApiSiteManagementRoute
  '/items/$itemSlug': typeof ItemsItemSlugRoute
  '/like/$tag': typeof LikeTagRoute
  '/people/$personSlug': typeof PeoplePersonSlugRoute
  '/tags/$tagSlug': typeof TagsTagSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/admin'
    | '/discover'
    | '/galaxy'
    | '/item-galaxy'
    | '/mcp'
    | '/og'
    | '/products'
    | '/tag-galaxy'
    | '/tags'
    | '/uses'
    | '/admin/awards'
    | '/admin/batch'
    | '/admin/errors'
    | '/admin/items'
    | '/admin/merge'
    | '/admin/review'
    | '/admin/scrape'
    | '/admin/tags'
    | '/admin/tools'
    | '/api/site-management'
    | '/items/$itemSlug'
    | '/like/$tag'
    | '/people/$personSlug'
    | '/tags/$tagSlug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/discover'
    | '/galaxy'
    | '/item-galaxy'
    | '/mcp'
    | '/og'
    | '/products'
    | '/tag-galaxy'
    | '/tags'
    | '/uses'
    | '/admin/awards'
    | '/admin/batch'
    | '/admin/errors'
    | '/admin/items'
    | '/admin/merge'
    | '/admin/review'
    | '/admin/scrape'
    | '/admin/tags'
    | '/admin/tools'
    | '/api/site-management'
    | '/items/$itemSlug'
    | '/like/$tag'
    | '/people/$personSlug'
    | '/tags/$tagSlug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/admin'
    | '/discover'
    | '/galaxy'
    | '/item-galaxy'
    | '/mcp'
    | '/og'
    | '/products'
    | '/tag-galaxy'
    | '/tags'
    | '/uses'
    | '/admin/awards'
    | '/admin/batch'
    | '/admin/errors'
    | '/admin/items'
    | '/admin/merge'
    | '/admin/review'
    | '/admin/scrape'
    | '/admin/tags'
    | '/admin/tools'
    | '/api/site-management'
    | '/items/$itemSlug'
    | '/like/$tag'
    | '/people/$personSlug'
    | '/tags/$tagSlug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  AdminRoute: typeof AdminRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  GalaxyRoute: typeof GalaxyRoute
  ItemGalaxyRoute: typeof ItemGalaxyRoute
  McpRoute: typeof McpRoute
  OgRoute: typeof OgRoute
  ProductsRoute: typeof ProductsRoute
  TagGalaxyRoute: typeof TagGalaxyRoute
  TagsRoute: typeof TagsRouteWithChildren
  UsesRoute: typeof UsesRoute
  ApiSiteManagementRoute: typeof ApiSiteManagementRoute
  ItemsItemSlugRoute: typeof ItemsItemSlugRoute
  LikeTagRoute: typeof LikeTagRoute
  PeoplePersonSlugRoute: typeof PeoplePersonSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uses': {
      id: '/uses'
      path: '/uses'
      fullPath: '/uses'
      preLoaderRoute: typeof UsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag-galaxy': {
      id: '/tag-galaxy'
      path: '/tag-galaxy'
      fullPath: '/tag-galaxy'
      preLoaderRoute: typeof TagGalaxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item-galaxy': {
      id: '/item-galaxy'
      path: '/item-galaxy'
      fullPath: '/item-galaxy'
      preLoaderRoute: typeof ItemGalaxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galaxy': {
      id: '/galaxy'
      path: '/galaxy'
      fullPath: '/galaxy'
      preLoaderRoute: typeof GalaxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tags/$tagSlug': {
      id: '/tags/$tagSlug'
      path: '/$tagSlug'
      fullPath: '/tags/$tagSlug'
      preLoaderRoute: typeof TagsTagSlugRouteImport
      parentRoute: typeof TagsRoute
    }
    '/people/$personSlug': {
      id: '/people/$personSlug'
      path: '/people/$personSlug'
      fullPath: '/people/$personSlug'
      preLoaderRoute: typeof PeoplePersonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/like/$tag': {
      id: '/like/$tag'
      path: '/like/$tag'
      fullPath: '/like/$tag'
      preLoaderRoute: typeof LikeTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$itemSlug': {
      id: '/items/$itemSlug'
      path: '/items/$itemSlug'
      fullPath: '/items/$itemSlug'
      preLoaderRoute: typeof ItemsItemSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site-management': {
      id: '/api/site-management'
      path: '/api/site-management'
      fullPath: '/api/site-management'
      preLoaderRoute: typeof ApiSiteManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tools': {
      id: '/admin/tools'
      path: '/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AdminToolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scrape': {
      id: '/admin/scrape'
      path: '/scrape'
      fullPath: '/admin/scrape'
      preLoaderRoute: typeof AdminScrapeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/merge': {
      id: '/admin/merge'
      path: '/merge'
      fullPath: '/admin/merge'
      preLoaderRoute: typeof AdminMergeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/items': {
      id: '/admin/items'
      path: '/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof AdminItemsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/errors': {
      id: '/admin/errors'
      path: '/errors'
      fullPath: '/admin/errors'
      preLoaderRoute: typeof AdminErrorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/batch': {
      id: '/admin/batch'
      path: '/batch'
      fullPath: '/admin/batch'
      preLoaderRoute: typeof AdminBatchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/awards': {
      id: '/admin/awards'
      path: '/awards'
      fullPath: '/admin/awards'
      preLoaderRoute: typeof AdminAwardsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAwardsRoute: typeof AdminAwardsRoute
  AdminBatchRoute: typeof AdminBatchRoute
  AdminErrorsRoute: typeof AdminErrorsRoute
  AdminItemsRoute: typeof AdminItemsRoute
  AdminMergeRoute: typeof AdminMergeRoute
  AdminReviewRoute: typeof AdminReviewRoute
  AdminScrapeRoute: typeof AdminScrapeRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminToolsRoute: typeof AdminToolsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAwardsRoute: AdminAwardsRoute,
  AdminBatchRoute: AdminBatchRoute,
  AdminErrorsRoute: AdminErrorsRoute,
  AdminItemsRoute: AdminItemsRoute,
  AdminMergeRoute: AdminMergeRoute,
  AdminReviewRoute: AdminReviewRoute,
  AdminScrapeRoute: AdminScrapeRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminToolsRoute: AdminToolsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TagsRouteChildren {
  TagsTagSlugRoute: typeof TagsTagSlugRoute
}

const TagsRouteChildren: TagsRouteChildren = {
  TagsTagSlugRoute: TagsTagSlugRoute,
}

const TagsRouteWithChildren = TagsRoute._addFileChildren(TagsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  AdminRoute: AdminRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  GalaxyRoute: GalaxyRoute,
  ItemGalaxyRoute: ItemGalaxyRoute,
  McpRoute: McpRoute,
  OgRoute: OgRoute,
  ProductsRoute: ProductsRoute,
  TagGalaxyRoute: TagGalaxyRoute,
  TagsRoute: TagsRouteWithChildren,
  UsesRoute: UsesRoute,
  ApiSiteManagementRoute: ApiSiteManagementRoute,
  ItemsItemSlugRoute: ItemsItemSlugRoute,
  LikeTagRoute: LikeTagRoute,
  PeoplePersonSlugRoute: PeoplePersonSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
