/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagsTagSlugRouteImport } from './routes/tags.$tagSlug'
import { Route as PeoplePersonSlugRouteImport } from './routes/people.$personSlug'
import { Route as LikeTagRouteImport } from './routes/like/$tag'
import { Route as ApiScrapePersonSlugRouteImport } from './routes/api.scrape.$personSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagSlugRoute = TagsTagSlugRouteImport.update({
  id: '/tags/$tagSlug',
  path: '/tags/$tagSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PeoplePersonSlugRoute = PeoplePersonSlugRouteImport.update({
  id: '/people/$personSlug',
  path: '/people/$personSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LikeTagRoute = LikeTagRouteImport.update({
  id: '/like/$tag',
  path: '/like/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScrapePersonSlugRoute = ApiScrapePersonSlugRouteImport.update({
  id: '/api/scrape/$personSlug',
  path: '/api/scrape/$personSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/like/$tag': typeof LikeTagRoute
  '/people/$personSlug': typeof PeoplePersonSlugRoute
  '/tags/$tagSlug': typeof TagsTagSlugRoute
  '/api/scrape/$personSlug': typeof ApiScrapePersonSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/like/$tag': typeof LikeTagRoute
  '/people/$personSlug': typeof PeoplePersonSlugRoute
  '/tags/$tagSlug': typeof TagsTagSlugRoute
  '/api/scrape/$personSlug': typeof ApiScrapePersonSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/like/$tag': typeof LikeTagRoute
  '/people/$personSlug': typeof PeoplePersonSlugRoute
  '/tags/$tagSlug': typeof TagsTagSlugRoute
  '/api/scrape/$personSlug': typeof ApiScrapePersonSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/like/$tag'
    | '/people/$personSlug'
    | '/tags/$tagSlug'
    | '/api/scrape/$personSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/like/$tag'
    | '/people/$personSlug'
    | '/tags/$tagSlug'
    | '/api/scrape/$personSlug'
  id:
    | '__root__'
    | '/'
    | '/like/$tag'
    | '/people/$personSlug'
    | '/tags/$tagSlug'
    | '/api/scrape/$personSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LikeTagRoute: typeof LikeTagRoute
  PeoplePersonSlugRoute: typeof PeoplePersonSlugRoute
  TagsTagSlugRoute: typeof TagsTagSlugRoute
  ApiScrapePersonSlugRoute: typeof ApiScrapePersonSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$tagSlug': {
      id: '/tags/$tagSlug'
      path: '/tags/$tagSlug'
      fullPath: '/tags/$tagSlug'
      preLoaderRoute: typeof TagsTagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$personSlug': {
      id: '/people/$personSlug'
      path: '/people/$personSlug'
      fullPath: '/people/$personSlug'
      preLoaderRoute: typeof PeoplePersonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/like/$tag': {
      id: '/like/$tag'
      path: '/like/$tag'
      fullPath: '/like/$tag'
      preLoaderRoute: typeof LikeTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scrape/$personSlug': {
      id: '/api/scrape/$personSlug'
      path: '/api/scrape/$personSlug'
      fullPath: '/api/scrape/$personSlug'
      preLoaderRoute: typeof ApiScrapePersonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LikeTagRoute: LikeTagRoute,
  PeoplePersonSlugRoute: PeoplePersonSlugRoute,
  TagsTagSlugRoute: TagsTagSlugRoute,
  ApiScrapePersonSlugRoute: ApiScrapePersonSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
