/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WallOfShameRouteImport } from './routes/wall-of-shame'
import { Route as UsesRouteImport } from './routes/uses'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as OgRouteImport } from './routes/og'
import { Route as ItemsDashboardRouteImport } from './routes/items-dashboard'
import { Route as GalaxyRouteImport } from './routes/galaxy'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagsTagSlugRouteImport } from './routes/tags.$tagSlug'
import { Route as PeoplePersonSlugRouteImport } from './routes/people.$personSlug'
import { Route as LikeTagRouteImport } from './routes/like/$tag'
import { Route as ItemsItemSlugRouteImport } from './routes/items.$itemSlug'

const WallOfShameRoute = WallOfShameRouteImport.update({
  id: '/wall-of-shame',
  path: '/wall-of-shame',
  getParentRoute: () => rootRouteImport,
} as any)
const UsesRoute = UsesRouteImport.update({
  id: '/uses',
  path: '/uses',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsDashboardRoute = ItemsDashboardRouteImport.update({
  id: '/items-dashboard',
  path: '/items-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GalaxyRoute = GalaxyRouteImport.update({
  id: '/galaxy',
  path: '/galaxy',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagSlugRoute = TagsTagSlugRouteImport.update({
  id: '/$tagSlug',
  path: '/$tagSlug',
  getParentRoute: () => TagsRoute,
} as any)
const PeoplePersonSlugRoute = PeoplePersonSlugRouteImport.update({
  id: '/people/$personSlug',
  path: '/people/$personSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LikeTagRoute = LikeTagRouteImport.update({
  id: '/like/$tag',
  path: '/like/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsItemSlugRoute = ItemsItemSlugRouteImport.update({
  id: '/items/$itemSlug',
  path: '/items/$itemSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/galaxy': typeof GalaxyRoute
  '/items-dashboard': typeof ItemsDashboardRoute
  '/og': typeof OgRoute
  '/tags': typeof TagsRouteWithChildren
  '/uses': typeof UsesRoute
  '/wall-of-shame': typeof WallOfShameRoute
  '/items/$itemSlug': typeof ItemsItemSlugRoute
  '/like/$tag': typeof LikeTagRoute
  '/people/$personSlug': typeof PeoplePersonSlugRoute
  '/tags/$tagSlug': typeof TagsTagSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/galaxy': typeof GalaxyRoute
  '/items-dashboard': typeof ItemsDashboardRoute
  '/og': typeof OgRoute
  '/tags': typeof TagsRouteWithChildren
  '/uses': typeof UsesRoute
  '/wall-of-shame': typeof WallOfShameRoute
  '/items/$itemSlug': typeof ItemsItemSlugRoute
  '/like/$tag': typeof LikeTagRoute
  '/people/$personSlug': typeof PeoplePersonSlugRoute
  '/tags/$tagSlug': typeof TagsTagSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/galaxy': typeof GalaxyRoute
  '/items-dashboard': typeof ItemsDashboardRoute
  '/og': typeof OgRoute
  '/tags': typeof TagsRouteWithChildren
  '/uses': typeof UsesRoute
  '/wall-of-shame': typeof WallOfShameRoute
  '/items/$itemSlug': typeof ItemsItemSlugRoute
  '/like/$tag': typeof LikeTagRoute
  '/people/$personSlug': typeof PeoplePersonSlugRoute
  '/tags/$tagSlug': typeof TagsTagSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/dashboard'
    | '/discover'
    | '/galaxy'
    | '/items-dashboard'
    | '/og'
    | '/tags'
    | '/uses'
    | '/wall-of-shame'
    | '/items/$itemSlug'
    | '/like/$tag'
    | '/people/$personSlug'
    | '/tags/$tagSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/dashboard'
    | '/discover'
    | '/galaxy'
    | '/items-dashboard'
    | '/og'
    | '/tags'
    | '/uses'
    | '/wall-of-shame'
    | '/items/$itemSlug'
    | '/like/$tag'
    | '/people/$personSlug'
    | '/tags/$tagSlug'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/dashboard'
    | '/discover'
    | '/galaxy'
    | '/items-dashboard'
    | '/og'
    | '/tags'
    | '/uses'
    | '/wall-of-shame'
    | '/items/$itemSlug'
    | '/like/$tag'
    | '/people/$personSlug'
    | '/tags/$tagSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  GalaxyRoute: typeof GalaxyRoute
  ItemsDashboardRoute: typeof ItemsDashboardRoute
  OgRoute: typeof OgRoute
  TagsRoute: typeof TagsRouteWithChildren
  UsesRoute: typeof UsesRoute
  WallOfShameRoute: typeof WallOfShameRoute
  ItemsItemSlugRoute: typeof ItemsItemSlugRoute
  LikeTagRoute: typeof LikeTagRoute
  PeoplePersonSlugRoute: typeof PeoplePersonSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wall-of-shame': {
      id: '/wall-of-shame'
      path: '/wall-of-shame'
      fullPath: '/wall-of-shame'
      preLoaderRoute: typeof WallOfShameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uses': {
      id: '/uses'
      path: '/uses'
      fullPath: '/uses'
      preLoaderRoute: typeof UsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items-dashboard': {
      id: '/items-dashboard'
      path: '/items-dashboard'
      fullPath: '/items-dashboard'
      preLoaderRoute: typeof ItemsDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galaxy': {
      id: '/galaxy'
      path: '/galaxy'
      fullPath: '/galaxy'
      preLoaderRoute: typeof GalaxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$tagSlug': {
      id: '/tags/$tagSlug'
      path: '/$tagSlug'
      fullPath: '/tags/$tagSlug'
      preLoaderRoute: typeof TagsTagSlugRouteImport
      parentRoute: typeof TagsRoute
    }
    '/people/$personSlug': {
      id: '/people/$personSlug'
      path: '/people/$personSlug'
      fullPath: '/people/$personSlug'
      preLoaderRoute: typeof PeoplePersonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/like/$tag': {
      id: '/like/$tag'
      path: '/like/$tag'
      fullPath: '/like/$tag'
      preLoaderRoute: typeof LikeTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$itemSlug': {
      id: '/items/$itemSlug'
      path: '/items/$itemSlug'
      fullPath: '/items/$itemSlug'
      preLoaderRoute: typeof ItemsItemSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TagsRouteChildren {
  TagsTagSlugRoute: typeof TagsTagSlugRoute
}

const TagsRouteChildren: TagsRouteChildren = {
  TagsTagSlugRoute: TagsTagSlugRoute,
}

const TagsRouteWithChildren = TagsRoute._addFileChildren(TagsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  GalaxyRoute: GalaxyRoute,
  ItemsDashboardRoute: ItemsDashboardRoute,
  OgRoute: OgRoute,
  TagsRoute: TagsRouteWithChildren,
  UsesRoute: UsesRoute,
  WallOfShameRoute: WallOfShameRoute,
  ItemsItemSlugRoute: ItemsItemSlugRoute,
  LikeTagRoute: LikeTagRoute,
  PeoplePersonSlugRoute: PeoplePersonSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
